CREATE USER USR WITH ENCRYPTED PASSWORD 'PASSWORD';
GRANT  CONNECT ON DATABASE DB  TO USR;
GRANT  USAGE   ON SCHEMA public  TO USR;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES  IN SCHEMA public TO USR;
ALTER USER USR SET search_path TO public;
