using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Soanx.TelegramModels;

public enum MessageContentType {
    None = 0,
    MessageChatChangeTitle = 1,
    MessageAnimatedEmoji = 2,
    MessageAnimation = 3,
    MessageAudio = 4,
    MessageBasicGroupChatCreate = 5,
    MessageCall = 6,
    MessageChatAddMembers = 7,
    MessageChatChangePhoto = 8,
    MessageChatDeleteMember = 9,
    MessageChatDeletePhoto = 10,
    MessageChatJoinByLink = 11,
    MessageChatJoinByRequest = 12,
    MessageChatSetTheme = 13,
    MessageChatSetTtl = 14,
    MessageChatUpgradeFrom = 15,
    MessageChatUpgradeTo = 16,
    MessageContact = 17,
    MessageContactRegistered = 18,
    MessageCustomServiceAction = 19,
    MessageDice = 20,
    MessageDocument = 21,
    MessageExpiredPhoto = 22,
    MessageExpiredVideo = 23,
    MessageForumTopicCreated = 24,
    MessageForumTopicEdited = 25,
    MessageForumTopicIsClosedToggled = 26,
    MessageForumTopicIsHiddenToggled = 27,
    MessageGame = 28,
    MessageGameScore = 29,
    MessageGiftedPremium = 30,
    MessageInviteVideoChatParticipants = 31,
    MessageInvoice = 32,
    MessageLocation = 33,
    MessagePassportDataReceived = 34,
    MessagePassportDataSent = 35,
    MessagePaymentSuccessful = 36,
    MessagePaymentSuccessfulBot = 37,
    MessagePhoto = 38,
    MessagePinMessage = 39,
    MessagePoll = 40,
    MessageProximityAlertTriggered = 41,
    MessageScreenshotTaken = 42,
    MessageSticker = 43,
    MessageSupergroupChatCreate = 44,
    MessageText = 45,
    MessageUnsupported = 46,
    MessageVenue = 47,
    MessageVideo = 48,
    MessageVideoChatEnded = 49,
    MessageVideoChatScheduled = 50,
    MessageVideoChatStarted = 51,
    MessageVideoNote = 52,
    MessageVoiceNote = 53,
    MessageWebAppDataReceived = 54,
    MessageWebAppDataSent = 55,
    MessageWebsiteConnected = 56
}
